### PR TITLE
feat(danger): Add GH action for DangerJS PR linter

### PR DESCRIPTION
**Pull request by tomassebestik**
Add GH action for DangerJS linter for Espressif projects.

## Related
- https://jira.espressif.com:8443/browse/RDT-492

### CODE REVIEW

**Comment by tomassebestik** [comment]
@kumekay @radimkarnis @igrr PTAL ... the result (usage) can be seen in [demo repo](https://github.com/tomassebestik/test-repo-labels/pull/1#issuecomment-1630341320)
***
Note: I touched a bit the file `update_submodule_versions/entrypoint.sh` ... shellcheck GH action running in this repo was complaining (we have set severity quiet high and it is failing even with warnings):
```sh
./update_submodule_versions/entrypoint.sh:8:10: note: Double quote to prevent globbing and word splitting. [SC2086]
./update_submodule_versions/entrypoint.sh:9:23: note: Double quote to prevent globbing and word splitting. [SC2086]
```
I have added quotes as suggested.

**Comment by kumekay** [comment]
@tomassebestik This is an action, not a reusable workflow, right?

**Review by kumekay — APPROVED** [review]
Thank you @tomassebestik LGTM

**Comment by tomassebestik** [comment]
> @tomassebestik This is an action, not a reusable workflow, right?

Yes, it is GH action .... I corrected the terminology in docs, thank you.

**Review by kumekay — APPROVED** [review]

**Pull request merged**
